### ISSUE TITLE
Issues With Items Having Metadata

### ISSUE THREAD

**Issue by mrtechtroid** [SmallJoker/exchange_shop#1]
Recently This Mod was Introduced to Multicraft Servers And I Wanted To Use Them To Sell Written Books.
But When I Put The Written Books Into The Exchange Shop and then used an alt to try to test if I can buy them I saw that the I received an empty book "Book With Text" with the content removed off. 
This May Be Due To The Metadata Being Removed off when getting the item using the exchange button. 

I Would Like You To Fix This Issue. 
Thanks!

**Comment by SmallJoker** [comment]
I Found A Solution For This Issue. Please Check Whether The Following Commit Works As Expected.
-> 5122b5a

**Comment by mrtechtroid** [comment]
Works Great. Thanks For The Fix!
